# Generated by Django 2.2.3 on 2019-08-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_submenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
