# Generated by Django 2.2.3 on 2019-07-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_menu_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
    ]
