# Generated by Django 2.2.3 on 2019-07-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Menu'),
        ),
    ]
