# Generated by Django 2.2.3 on 2019-07-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Menu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
