# Generated by Django 2.2.3 on 2019-07-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190731_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
