# Generated by Django 2.2.3 on 2019-07-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190731_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
