# Generated by Django 2.2.4 on 2019-08-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190807_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='simple-is-better-than-nothing'),
            preserve_default=False,
        ),
    ]
