# Generated by Django 2.2.4 on 2019-08-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190823_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='simple-is-better-than-nothing'),
            preserve_default=False,
        ),
    ]
